# Generated by Django 5.2.9 on 2026-01-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_therapysession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='Слово або фраза')),
                ('score', models.FloatField(verbose_name='Вага (-1.0 до 1.0)')),
            ],
        ),
    ]
